name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: aergus/latex
    steps:
      - name: Set up Git repository
        run: latexmk main.tex
