name: Gitea Actions Demo
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v3
  compile:
    container:
      image: aergus/latex
    steps:
      - name: Set up Git repository
        run: latexmk main.tex
